Create TABLE TABLE_NOTNULL
(
    LOGIN_ID  varchar2(20) not null,
    LOGIN_PWD varchar2(20) not null,
    TEL       VARCHAR2(20)
);

select *
from TABLE_NOTNULL;

insert into TABLE_NOTNULL
values ('TEST_ID_01', '1234', '010-1234-5678');

SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
from USER_CONSTRAINTS
where TABLE_NAME = 'TABLE_NOTNULL';
-- CONSTRAINT 확인하는 쿼리

SELECT *
from USER_IND_COLUMNS;

ALTER TABLE TABLE_NOTNULL
    MODIFY TEL NUll;

select *
from TABLE_NOTNULL;

CREATE TABLE TABLE_UNIQUE
(
    LOGIN_ID  VARCHAR2(20) UNIQUE,
    LOGIN_PWD VARCHAR2(20) NOT NULL,
    TEL       VARCHAR2(20)
);

select *
from TABLE_UNIQUE;

SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
from USER_CONSTRAINTS
where TABLE_NAME = 'TABLE_UNIQUE';

select * from USER_IND_COLUMNS;
-- UNIQUE 제한조건도 인덱스가 자동 생성됨

insert into TABLE_UNIQUE VALUES ('12','12','12');
insert into TABLE_UNIQUE VALUES ('123','12','132');
insert into TABLE_UNIQUE VALUES (null,'12','12');
insert into TABLE_UNIQUE VALUES (null,'12','12');
-- null값을 넣을 수 있고 null값은 중복이 되지 않음

ALTER TABLE TABLE_UNIQUE MODIFY TEL CONSTRAINT TEL_UNIQUE UNIQUE;
